### ISSUE TITLE
Setting Authorization header

### ISSUE THREAD

**Issue by jameskolce** [h2non/theon#56]
I'm trying to connect to the Dribbble API using Theon, everything is working fine so far, but I just have a little doubt: When I set the `Authorization` header, it only works after reloading the page twice, so I'm not sure it I'm doing this the right way, here is part of the code (without extra details):

```js

// ...

const client = Theon(settings.dribbble.url)
  .type('json')
  .use((req, res, next) => {
    req.root.persistHeader('Authorization', 'Bearer XXXXXXXXXXX');
    next();
  });

client.collection('shots').basePath('/shots').action('find');

const dribbbleAPI = client.render();

// ...

server.route({
  method: 'GET',
  path: '/',
  handler: (request, reply) => {
    dribbbleAPI.shots.find().end((err, res) => {
      // ...
    });
  }
});
```

So after running the server and reloading the page I get a message of bad credentials from Dribbble but after reloading the page again then I get the data as expected. 
I suppose is not a big deal because it only happens at the first try but I just want to be sure, thanks!

**Comment by h2non** [comment]
Looks like the token is not available when the middleware is triggered. You can debug things a bit, such as adding a console.log statement in the global middleware ensuring the header value properly exists.

**Comment by jameskolce** [comment]
But I'm using a string directly in the header value so is always available I think.

I'm not sure how to get the header as you mention but I did this:

```
client.observe('after response', function (req, res, next) {
  console.log('Log response:', req.headers)
  next()
})
```

And when I reload the page I get:

```
Log response: { 'content-type': 'application/json' }
```

The second time I reload the page I get:

```
Log response: { 'content-type': 'application/json', authorization: 'Bearer XXXXXXXXXXX' }
```

I tested the Dribbble API with Postman and I get the data at the first try so I'm guessing is something on the way I'm doing this.

Here is some info about the API:
http://developer.dribbble.com/v1/#authentication

So I also tried with:

```
req.root.persistQueryParam('access_token', 'XXXXXXXXXXX');
```

But is the same thing, maybe I'm doing something wrong? Are `req.root.persistHeader` and `req.root.persistQueryParam` the right methods for this?

**Comment by h2non** [comment]
Yes, persistHeader is totally fine for this purpose.

For some reason, the header is not defined properly, and I think this is relate to some inconsistent logic in the server flow. 

I would say that you should authenticate theon client before you start accepting traffic in your server, therefore do not start the server until you have theon configured.

I would probably need to test some code to help you better.

**Comment by jameskolce** [comment]
Yeah so I think the flow in the server is okay, at least I don't see any other way I can put it but that's the most probable thing, that I'm setting it up in a slightly wrong way. But to fix this right now I'm just sending a request to Dribbble after rendering the client, so when the server is started and the page is loaded on the browser, the header is already set.

But I'll give you access to the repository in case you can and want to take a look, is not a problem if you don't have time for the moment, though, so whenever you want to take a look!

**Comment by h2non** [comment]
Will take a look in detail, but for that escenario I think you can simply expose the header on every request vía middleware without mutating the global root config. 
That's for what it was designed.

**Comment by jameskolce** [comment]
Thanks a lot! But I'm not quite sure about how to expose the header as you say, is there any example? I was looking at the documentation but I can't find how. Thanks again.

**Comment by tomas-fp** [comment]
You can use this method:
https://github.com/h2non/theon#requestsetname-value

Example:
```js
const client = Theon(settings.dribbble.url)
  .type('json')
  // Header should be persisted at global level
  .set('Authorization', 'Bearer XXXXXXXXXXX')

// Declare the collections
client.collection('shots').basePath('/shots').action('find')

const dribbbleAPI = client.render()
```

Let me know if that works.

**Comment by jameskolce** [comment]
Great, that looks a lot better and I'll try in a moment, thanks a lot.

**Comment by jameskolce** [comment]
Yes, perfect, it works now. I just didn't know those methods could be used like that, but it seems obvious to me now :D 

Thanks!
